### PR TITLE
Fix/flaky tests

### LINKED ISSUE #384: TestE2EKafkaEvents::test_01_napp_sends_data_correctly is having reruns
We should enhance this test case below, on most execs it's having reruns, we should make it less prone to reruns, @Auwate can you take care of this?

```
RERUN tests/test_e2e_90_kafka_events.py::TestE2EKafkaEvents::test_01_napp_sends_data_correctly


rerun: 0
tests/test_e2e_90_kafka_events.py::TestE2EKafkaEvents::test_01_napp_sends_data_correctly: 2025-09-09,18:50:27.093402 - 2025-09-09,18:50:30.886135
self = <tests.test_e2e_90_kafka_events.TestE2EKafkaEvents object at 0x7f96ad4770d0>
    async def test_01_napp_sends_data_correctly(self):
        """
        Test that kafka_events correctly runs the 'setup' method. This would require
        that the AIOKafkaProducer has been properly initialized
        """
        # Create a consumer before the message is propagated to reduce the amount of messages
    
        consumer = AIOKafkaConsumer(
            (KAFKA_TOPIC),
            bootstrap_servers=KAFKA_ADDRESSES,
        )
    
        await consumer.start()
    
        # Create an EVC-creation event to send to Kafka
    
        evc_name = "Vlan_%s" % 902
    
        payload = {
            "name": evc_name,
            "enabled": True,
            "dynamic_backup_path": True,
            "uni_a": {
                "interface_id": "00:00:00:00:00:00:00:01:1",
                "tag": {"tag_type": "vlan", "value": 902}
            },
            "uni_z": {
                "interface_id": "00:00:00:00:00:00:00:03:1",
                "tag": {"tag_type": "vlan", "value": 902}
            }
        }
        api_url = KYTOS_API + '/mef_eline/v2/evc/'
        response = requests.post(
            api_url,
            data=json.dumps(payload),
            headers={'Content-type': 'application/json'},
            timeout=5
        )
    
        assert response.status_code == 201, response.text
    
        # Wait for the message to propagate
    
        await asyncio.sleep(3)
    
        # Collect the message from Kafka
    
        try:
            # Wait up to 1 second for messages
            results = await consumer.getmany(timeout_ms=1000)
    
            # Ensure values exist
            assert results.values()
    
            found = False
    
            for messages in results.values():
                for msg in messages:
                    event = json.loads(msg.value.decode())
                    if event["event"] == 'kytos/mef_eline.created':
                        found = True
                        break
    
>           assert found
E           assert False
tests/test_e2e_90_kafka_events.py:149: AssertionError
=========================== rerun test summary info ============================
```

### PR DESCRIPTION
**Pull request by Auwate**
Closes #384 

### Summary

Enhanced the test logic to pull multiple times, rather than wait long periods. This reduces flakiness by allowing for more data to be sent from Kafka **and** allows more time for the data to propagate.

### End-to-End Tests

Ran multiple tests via the GitLab manual runner, showing `<= 1` reruns max.

### CODE REVIEW

File: kytos-init.sh [hunk 1]
```diff
@@ -35,9 +35,9 @@ test -z "$RERUNS" && RERUNS=2
...
 
-python3 -m pytest $TESTS --reruns $RERUNS -r fEr
+#python3 -m pytest $TESTS --reruns $RERUNS -r fEr
 
 #tail -f
 
 # only run specific test
-# python3 -m pytest --timeout=60 tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_on_primary_path_fail_should_migrate_to_backup
\ No newline at end of file
+python3 -m pytest tests/test_e2e_90_kafka_events.py --reruns 10 -r fEr
```
Comment (viniarck) [inline kytos-init.sh:43]: The local kytos-init.sh change was committed, if you can revert it.

File: tests/test_e2e_90_kafka_events.py [hunk 2]
```diff
@@ -126,27 +126,34 @@ async def test_01_napp_sends_data_correctly(self):
...
 
-        # Collect the message from Kafka
+            if found:
+                break
 
-        try:
-            # Wait up to 1 second for messages
-            results = await consumer.getmany(timeout_ms=1000)
+            try:
+                # Wait up to 1 second for messages
```
Comment (viniarck) [inline tests/test_e2e_90_kafka_events.py:141]: This comment is no longer accurate, can you update or delete it?

**Review by viniarck — COMMENTED** [review]
Overall looks good @Auwate, just minor code changes clean up remaining.

File: kytos-init.sh (hunk 1 above)
Comment (Auwate) [reply kytos-init.sh:43]: Ah, yes! Let me change this.

**Review by viniarck — APPROVED** [review]
